version: "3.8"

services:
  bookingdb:
    image: mysql:8
    container_name: bookingdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookingdb
    ports:
      - "3306:3306"
  bookingsystem:
    build: .
    container_name: bookingsystem
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bookingdb:3306/bookingdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - bookingdb
